/**
 * 그림(이모지) 퀴즈용 단어 — 구체 명사 한글 ↔ 이모지. Picture Quiz 전용.
 * 이모지=유니코드(라이선스 free). 한글·이모지 모두 고유(dedup).
 */

export interface EmojiWord {
  korean: string;
  gloss: string;
  emoji: string;
  category:
    | "food" | "animal" | "plant" | "nature" | "vehicle"
    | "clothing" | "activity" | "music" | "place" | "object" | "body";
}

export const EMOJI_WORDS: EmojiWord[] = [
  { korean: "사과", gloss: "apple", emoji: "🍎", category: "food" },
  { korean: "바나나", gloss: "banana", emoji: "🍌", category: "food" },
  { korean: "수박", gloss: "watermelon", emoji: "🍉", category: "food" },
  { korean: "딸기", gloss: "strawberry", emoji: "🍓", category: "food" },
  { korean: "포도", gloss: "grapes", emoji: "🍇", category: "food" },
  { korean: "빵", gloss: "bread", emoji: "🍞", category: "food" },
  { korean: "밥", gloss: "rice", emoji: "🍚", category: "food" },
  { korean: "라면", gloss: "ramen", emoji: "🍜", category: "food" },
  { korean: "피자", gloss: "pizza", emoji: "🍕", category: "food" },
  { korean: "치킨", gloss: "chicken", emoji: "🍗", category: "food" },
  { korean: "커피", gloss: "coffee", emoji: "☕", category: "food" },
  { korean: "우유", gloss: "milk", emoji: "🥛", category: "food" },
  { korean: "계란", gloss: "egg", emoji: "🥚", category: "food" },
  { korean: "물", gloss: "water", emoji: "💧", category: "food" },
  { korean: "오렌지", gloss: "orange", emoji: "🍊", category: "food" },
  { korean: "레몬", gloss: "lemon", emoji: "🍋", category: "food" },
  { korean: "토마토", gloss: "tomato", emoji: "🍅", category: "food" },
  { korean: "당근", gloss: "carrot", emoji: "🥕", category: "food" },
  { korean: "옥수수", gloss: "corn", emoji: "🌽", category: "food" },
  { korean: "감자", gloss: "potato", emoji: "🥔", category: "food" },
  { korean: "버섯", gloss: "mushroom", emoji: "🍄", category: "food" },
  { korean: "햄버거", gloss: "hamburger", emoji: "🍔", category: "food" },
  { korean: "핫도그", gloss: "hot dog", emoji: "🌭", category: "food" },
  { korean: "아이스크림", gloss: "ice cream", emoji: "🍦", category: "food" },
  { korean: "케이크", gloss: "cake", emoji: "🍰", category: "food" },
  { korean: "초콜릿", gloss: "chocolate", emoji: "🍫", category: "food" },
  { korean: "쿠키", gloss: "cookie", emoji: "🍪", category: "food" },
  { korean: "도넛", gloss: "donut", emoji: "🍩", category: "food" },
  { korean: "치즈", gloss: "cheese", emoji: "🧀", category: "food" },
  { korean: "꿀", gloss: "honey", emoji: "🍯", category: "food" },
  { korean: "녹차", gloss: "green tea", emoji: "🍵", category: "food" },
  { korean: "와인", gloss: "wine", emoji: "🍷", category: "food" },
  { korean: "맥주", gloss: "beer", emoji: "🍺", category: "food" },
  { korean: "파인애플", gloss: "pineapple", emoji: "🍍", category: "food" },
  { korean: "망고", gloss: "mango", emoji: "🥭", category: "food" },
  { korean: "복숭아", gloss: "peach", emoji: "🍑", category: "food" },
  { korean: "체리", gloss: "cherry", emoji: "🍒", category: "food" },
  { korean: "키위", gloss: "kiwi", emoji: "🥝", category: "food" },
  { korean: "코코넛", gloss: "coconut", emoji: "🥥", category: "food" },
  { korean: "아보카도", gloss: "avocado", emoji: "🥑", category: "food" },
  { korean: "가지", gloss: "eggplant", emoji: "🍆", category: "food" },
  { korean: "브로콜리", gloss: "broccoli", emoji: "🥦", category: "food" },
  { korean: "고추", gloss: "chili", emoji: "🌶️", category: "food" },
  { korean: "마늘", gloss: "garlic", emoji: "🧄", category: "food" },
  { korean: "양파", gloss: "onion", emoji: "🧅", category: "food" },
  { korean: "밤", gloss: "chestnut", emoji: "🌰", category: "food" },
  { korean: "땅콩", gloss: "peanut", emoji: "🥜", category: "food" },
  { korean: "만두", gloss: "dumpling", emoji: "🥟", category: "food" },
  { korean: "초밥", gloss: "sushi", emoji: "🍣", category: "food" },
  { korean: "파스타", gloss: "pasta", emoji: "🍝", category: "food" },
  { korean: "카레", gloss: "curry", emoji: "🍛", category: "food" },
  { korean: "타코", gloss: "taco", emoji: "🌮", category: "food" },
  { korean: "팝콘", gloss: "popcorn", emoji: "🍿", category: "food" },
  { korean: "와플", gloss: "waffle", emoji: "🧇", category: "food" },
  { korean: "팬케이크", gloss: "pancake", emoji: "🥞", category: "food" },
  { korean: "감자튀김", gloss: "fries", emoji: "🍟", category: "food" },
  { korean: "푸딩", gloss: "pudding", emoji: "🍮", category: "food" },
  { korean: "사탕", gloss: "candy", emoji: "🍬", category: "food" },
  { korean: "막대사탕", gloss: "lollipop", emoji: "🍭", category: "food" },
  { korean: "주스", gloss: "juice", emoji: "🧃", category: "food" },
  { korean: "칵테일", gloss: "cocktail", emoji: "🍸", category: "food" },
  { korean: "차", gloss: "tea", emoji: "🫖", category: "food" },
  { korean: "소금", gloss: "salt", emoji: "🧂", category: "food" },
  { korean: "버터", gloss: "butter", emoji: "🧈", category: "food" },
  { korean: "블루베리", gloss: "blueberry", emoji: "🫐", category: "food" },
  { korean: "올리브", gloss: "olive", emoji: "🫒", category: "food" },
  { korean: "피망", gloss: "bell pepper", emoji: "🫑", category: "food" },
  { korean: "콩", gloss: "beans", emoji: "🫘", category: "food" },
  { korean: "생강", gloss: "ginger", emoji: "🫚", category: "food" },
  { korean: "완두콩", gloss: "peas", emoji: "🫛", category: "food" },
  { korean: "고구마", gloss: "sweet potato", emoji: "🍠", category: "food" },
  { korean: "멜론", gloss: "melon", emoji: "🍈", category: "food" },
  { korean: "어묵", gloss: "fish cake", emoji: "🍢", category: "food" },
  { korean: "경단", gloss: "dango", emoji: "🍡", category: "food" },
  { korean: "도시락", gloss: "bento", emoji: "🍱", category: "food" },
  { korean: "주먹밥", gloss: "rice ball", emoji: "🍙", category: "food" },
  { korean: "크루아상", gloss: "croissant", emoji: "🥐", category: "food" },
  { korean: "바게트", gloss: "baguette", emoji: "🥖", category: "food" },
  { korean: "베이글", gloss: "bagel", emoji: "🥯", category: "food" },
  { korean: "새우튀김", gloss: "fried shrimp", emoji: "🍤", category: "food" },
  { korean: "빙수", gloss: "shaved ice", emoji: "🍧", category: "food" },
  { korean: "보바", gloss: "bubble tea", emoji: "🧋", category: "food" },
  { korean: "사케", gloss: "sake", emoji: "🍶", category: "food" },
  { korean: "샴페인", gloss: "champagne", emoji: "🍾", category: "food" },
  { korean: "위스키", gloss: "whiskey", emoji: "🥃", category: "food" },
  { korean: "우유병", gloss: "baby bottle", emoji: "🍼", category: "food" },
  { korean: "개", gloss: "dog", emoji: "🐶", category: "animal" },
  { korean: "고양이", gloss: "cat", emoji: "🐱", category: "animal" },
  { korean: "토끼", gloss: "rabbit", emoji: "🐰", category: "animal" },
  { korean: "곰", gloss: "bear", emoji: "🐻", category: "animal" },
  { korean: "호랑이", gloss: "tiger", emoji: "🐯", category: "animal" },
  { korean: "돼지", gloss: "pig", emoji: "🐷", category: "animal" },
  { korean: "말", gloss: "horse", emoji: "🐴", category: "animal" },
  { korean: "닭", gloss: "chicken (animal)", emoji: "🐔", category: "animal" },
  { korean: "물고기", gloss: "fish", emoji: "🐟", category: "animal" },
  { korean: "새", gloss: "bird", emoji: "🐦", category: "animal" },
  { korean: "사자", gloss: "lion", emoji: "🦁", category: "animal" },
  { korean: "코끼리", gloss: "elephant", emoji: "🐘", category: "animal" },
  { korean: "원숭이", gloss: "monkey", emoji: "🐵", category: "animal" },
  { korean: "기린", gloss: "giraffe", emoji: "🦒", category: "animal" },
  { korean: "판다", gloss: "panda", emoji: "🐼", category: "animal" },
  { korean: "쥐", gloss: "mouse", emoji: "🐭", category: "animal" },
  { korean: "양", gloss: "sheep", emoji: "🐑", category: "animal" },
  { korean: "뱀", gloss: "snake", emoji: "🐍", category: "animal" },
  { korean: "거북이", gloss: "turtle", emoji: "🐢", category: "animal" },
  { korean: "개구리", gloss: "frog", emoji: "🐸", category: "animal" },
  { korean: "나비", gloss: "butterfly", emoji: "🦋", category: "animal" },
  { korean: "벌", gloss: "bee", emoji: "🐝", category: "animal" },
  { korean: "문어", gloss: "octopus", emoji: "🐙", category: "animal" },
  { korean: "고래", gloss: "whale", emoji: "🐳", category: "animal" },
  { korean: "펭귄", gloss: "penguin", emoji: "🐧", category: "animal" },
  { korean: "오리", gloss: "duck", emoji: "🦆", category: "animal" },
  { korean: "부엉이", gloss: "owl", emoji: "🦉", category: "animal" },
  { korean: "상어", gloss: "shark", emoji: "🦈", category: "animal" },
  { korean: "늑대", gloss: "wolf", emoji: "🐺", category: "animal" },
  { korean: "여우", gloss: "fox", emoji: "🦊", category: "animal" },
  { korean: "다람쥐", gloss: "squirrel", emoji: "🐿️", category: "animal" },
  { korean: "고슴도치", gloss: "hedgehog", emoji: "🦔", category: "animal" },
  { korean: "박쥐", gloss: "bat", emoji: "🦇", category: "animal" },
  { korean: "공작", gloss: "peacock", emoji: "🦚", category: "animal" },
  { korean: "앵무새", gloss: "parrot", emoji: "🦜", category: "animal" },
  { korean: "백조", gloss: "swan", emoji: "🦢", category: "animal" },
  { korean: "칠면조", gloss: "turkey", emoji: "🦃", category: "animal" },
  { korean: "병아리", gloss: "chick", emoji: "🐤", category: "animal" },
  { korean: "달팽이", gloss: "snail", emoji: "🐌", category: "animal" },
  { korean: "개미", gloss: "ant", emoji: "🐜", category: "animal" },
  { korean: "무당벌레", gloss: "ladybug", emoji: "🐞", category: "animal" },
  { korean: "거미", gloss: "spider", emoji: "🕷️", category: "animal" },
  { korean: "열대어", gloss: "tropical fish", emoji: "🐠", category: "animal" },
  { korean: "복어", gloss: "pufferfish", emoji: "🐡", category: "animal" },
  { korean: "돌고래", gloss: "dolphin", emoji: "🐬", category: "animal" },
  { korean: "물개", gloss: "seal", emoji: "🦭", category: "animal" },
  { korean: "악어", gloss: "crocodile", emoji: "🐊", category: "animal" },
  { korean: "도마뱀", gloss: "lizard", emoji: "🦎", category: "animal" },
  { korean: "공룡", gloss: "dinosaur", emoji: "🦕", category: "animal" },
  { korean: "코뿔소", gloss: "rhino", emoji: "🦏", category: "animal" },
  { korean: "하마", gloss: "hippo", emoji: "🦛", category: "animal" },
  { korean: "캥거루", gloss: "kangaroo", emoji: "🦘", category: "animal" },
  { korean: "고릴라", gloss: "gorilla", emoji: "🦍", category: "animal" },
  { korean: "낙타", gloss: "camel", emoji: "🐫", category: "animal" },
  { korean: "사슴", gloss: "deer", emoji: "🦌", category: "animal" },
  { korean: "염소", gloss: "goat", emoji: "🐐", category: "animal" },
  { korean: "소", gloss: "cow", emoji: "🐮", category: "animal" },
  { korean: "새우", gloss: "shrimp", emoji: "🦐", category: "animal" },
  { korean: "게", gloss: "crab", emoji: "🦀", category: "animal" },
  { korean: "오징어", gloss: "squid", emoji: "🦑", category: "animal" },
  { korean: "수달", gloss: "otter", emoji: "🦦", category: "animal" },
  { korean: "나무늘보", gloss: "sloth", emoji: "🦥", category: "animal" },
  { korean: "유니콘", gloss: "unicorn", emoji: "🦄", category: "animal" },
  { korean: "모기", gloss: "mosquito", emoji: "🦟", category: "animal" },
  { korean: "파리", gloss: "fly", emoji: "🪰", category: "animal" },
  { korean: "바퀴벌레", gloss: "cockroach", emoji: "🪳", category: "animal" },
  { korean: "귀뚜라미", gloss: "cricket", emoji: "🦗", category: "animal" },
  { korean: "지렁이", gloss: "worm", emoji: "🪱", category: "animal" },
  { korean: "전갈", gloss: "scorpion", emoji: "🦂", category: "animal" },
  { korean: "조개", gloss: "shell", emoji: "🐚", category: "animal" },
  { korean: "산호", gloss: "coral", emoji: "🪸", category: "animal" },
  { korean: "해파리", gloss: "jellyfish", emoji: "🪼", category: "animal" },
  { korean: "굴", gloss: "oyster", emoji: "🦪", category: "animal" },
  { korean: "비둘기", gloss: "dove", emoji: "🕊️", category: "animal" },
  { korean: "독수리", gloss: "eagle", emoji: "🦅", category: "animal" },
  { korean: "거위", gloss: "goose", emoji: "🪿", category: "animal" },
  { korean: "도도새", gloss: "dodo", emoji: "🦤", category: "animal" },
  { korean: "플라밍고", gloss: "flamingo", emoji: "🦩", category: "animal" },
  { korean: "너구리", gloss: "raccoon", emoji: "🦝", category: "animal" },
  { korean: "들소", gloss: "bison", emoji: "🦬", category: "animal" },
  { korean: "오랑우탄", gloss: "orangutan", emoji: "🦧", category: "animal" },
  { korean: "매머드", gloss: "mammoth", emoji: "🦣", category: "animal" },
  { korean: "라마", gloss: "llama", emoji: "🦙", category: "animal" },
  { korean: "코알라", gloss: "koala", emoji: "🐨", category: "animal" },
  { korean: "티라노", gloss: "T-rex", emoji: "🦖", category: "animal" },
  { korean: "새싹", gloss: "sprout", emoji: "🌱", category: "plant" },
  { korean: "클로버", gloss: "clover", emoji: "🍀", category: "plant" },
  { korean: "튤립", gloss: "tulip", emoji: "🌷", category: "plant" },
  { korean: "장미", gloss: "rose", emoji: "🌹", category: "plant" },
  { korean: "해바라기", gloss: "sunflower", emoji: "🌻", category: "plant" },
  { korean: "데이지", gloss: "daisy", emoji: "🌼", category: "plant" },
  { korean: "허브", gloss: "herb", emoji: "🌿", category: "plant" },
  { korean: "대나무", gloss: "bamboo", emoji: "🎋", category: "plant" },
  { korean: "꽃다발", gloss: "bouquet", emoji: "💐", category: "plant" },
  { korean: "해", gloss: "sun", emoji: "☀️", category: "nature" },
  { korean: "달", gloss: "moon", emoji: "🌙", category: "nature" },
  { korean: "별", gloss: "star", emoji: "⭐", category: "nature" },
  { korean: "비", gloss: "rain", emoji: "🌧️", category: "nature" },
  { korean: "눈", gloss: "snow", emoji: "❄️", category: "nature" },
  { korean: "구름", gloss: "cloud", emoji: "☁️", category: "nature" },
  { korean: "무지개", gloss: "rainbow", emoji: "🌈", category: "nature" },
  { korean: "꽃", gloss: "flower", emoji: "🌸", category: "nature" },
  { korean: "나무", gloss: "tree", emoji: "🌳", category: "nature" },
  { korean: "산", gloss: "mountain", emoji: "⛰️", category: "nature" },
  { korean: "바다", gloss: "sea", emoji: "🌊", category: "nature" },
  { korean: "불", gloss: "fire", emoji: "🔥", category: "nature" },
  { korean: "번개", gloss: "lightning", emoji: "⚡", category: "nature" },
  { korean: "눈사람", gloss: "snowman", emoji: "⛄", category: "nature" },
  { korean: "지구", gloss: "earth", emoji: "🌍", category: "nature" },
  { korean: "화산", gloss: "volcano", emoji: "🌋", category: "nature" },
  { korean: "선인장", gloss: "cactus", emoji: "🌵", category: "nature" },
  { korean: "단풍", gloss: "autumn leaf", emoji: "🍁", category: "nature" },
  { korean: "야자수", gloss: "palm tree", emoji: "🌴", category: "nature" },
  { korean: "잎", gloss: "leaf", emoji: "🍃", category: "nature" },
  { korean: "토네이도", gloss: "tornado", emoji: "🌪️", category: "nature" },
  { korean: "안개", gloss: "fog", emoji: "🌫️", category: "nature" },
  { korean: "혜성", gloss: "comet", emoji: "☄️", category: "nature" },
  { korean: "행성", gloss: "planet", emoji: "🪐", category: "nature" },
  { korean: "일출", gloss: "sunrise", emoji: "🌅", category: "nature" },
  { korean: "일몰", gloss: "sunset", emoji: "🌇", category: "nature" },
  { korean: "은하", gloss: "galaxy", emoji: "🌌", category: "nature" },
  { korean: "온천", gloss: "hot spring", emoji: "♨️", category: "nature" },
  { korean: "사막", gloss: "desert", emoji: "🏜️", category: "nature" },
  { korean: "섬", gloss: "island", emoji: "🏝️", category: "nature" },
  { korean: "해변", gloss: "beach", emoji: "🏖️", category: "nature" },
  { korean: "별똥별", gloss: "shooting star", emoji: "🌠", category: "nature" },
  { korean: "보름달", gloss: "full moon", emoji: "🌕", category: "nature" },
  { korean: "상록수", gloss: "evergreen", emoji: "🌲", category: "nature" },
  { korean: "비행기", gloss: "airplane", emoji: "✈️", category: "vehicle" },
  { korean: "기차", gloss: "train", emoji: "🚆", category: "vehicle" },
  { korean: "버스", gloss: "bus", emoji: "🚌", category: "vehicle" },
  { korean: "택시", gloss: "taxi", emoji: "🚕", category: "vehicle" },
  { korean: "자동차", gloss: "car", emoji: "🚗", category: "vehicle" },
  { korean: "자전거", gloss: "bicycle", emoji: "🚲", category: "vehicle" },
  { korean: "배", gloss: "ship", emoji: "🚢", category: "vehicle" },
  { korean: "트럭", gloss: "truck", emoji: "🚚", category: "vehicle" },
  { korean: "오토바이", gloss: "motorcycle", emoji: "🏍️", category: "vehicle" },
  { korean: "헬리콥터", gloss: "helicopter", emoji: "🚁", category: "vehicle" },
  { korean: "로켓", gloss: "rocket", emoji: "🚀", category: "vehicle" },
  { korean: "구급차", gloss: "ambulance", emoji: "🚑", category: "vehicle" },
  { korean: "경찰차", gloss: "police car", emoji: "🚓", category: "vehicle" },
  { korean: "요트", gloss: "sailboat", emoji: "⛵", category: "vehicle" },
  { korean: "카누", gloss: "canoe", emoji: "🛶", category: "vehicle" },
  { korean: "스쿠터", gloss: "scooter", emoji: "🛴", category: "vehicle" },
  { korean: "썰매", gloss: "sled", emoji: "🛷", category: "vehicle" },
  { korean: "우주선", gloss: "spaceship", emoji: "🛸", category: "vehicle" },
  { korean: "기관차", gloss: "locomotive", emoji: "🚂", category: "vehicle" },
  { korean: "트랙터", gloss: "tractor", emoji: "🚜", category: "vehicle" },
  { korean: "소방차", gloss: "fire engine", emoji: "🚒", category: "vehicle" },
  { korean: "지하철", gloss: "metro", emoji: "🚇", category: "vehicle" },
  { korean: "전차", gloss: "tram", emoji: "🚊", category: "vehicle" },
  { korean: "케이블카", gloss: "cable car", emoji: "🚠", category: "vehicle" },
  { korean: "낙하산", gloss: "parachute", emoji: "🪂", category: "vehicle" },
  { korean: "닻", gloss: "anchor", emoji: "⚓", category: "vehicle" },
  { korean: "모터보트", gloss: "speedboat", emoji: "🚤", category: "vehicle" },
  { korean: "여객선", gloss: "liner", emoji: "🛳️", category: "vehicle" },
  { korean: "신호등", gloss: "traffic light", emoji: "🚦", category: "vehicle" },
  { korean: "주유소", gloss: "gas station", emoji: "⛽", category: "vehicle" },
  { korean: "장갑", gloss: "gloves", emoji: "🧤", category: "clothing" },
  { korean: "목도리", gloss: "scarf", emoji: "🧣", category: "clothing" },
  { korean: "코트", gloss: "coat", emoji: "🧥", category: "clothing" },
  { korean: "드레스", gloss: "dress", emoji: "👗", category: "clothing" },
  { korean: "넥타이", gloss: "necktie", emoji: "👔", category: "clothing" },
  { korean: "부츠", gloss: "boots", emoji: "👢", category: "clothing" },
  { korean: "하이힐", gloss: "high heels", emoji: "👠", category: "clothing" },
  { korean: "지갑", gloss: "purse", emoji: "👛", category: "clothing" },
  { korean: "선글라스", gloss: "sunglasses", emoji: "🕶️", category: "clothing" },
  { korean: "반지", gloss: "ring", emoji: "💍", category: "clothing" },
  { korean: "왕관", gloss: "crown", emoji: "👑", category: "clothing" },
  { korean: "실크햇", gloss: "top hat", emoji: "🎩", category: "clothing" },
  { korean: "졸업모자", gloss: "grad cap", emoji: "🎓", category: "clothing" },
  { korean: "헬멧", gloss: "helmet", emoji: "⛑️", category: "clothing" },
  { korean: "기모노", gloss: "kimono", emoji: "👘", category: "clothing" },
  { korean: "핸드백", gloss: "handbag", emoji: "👜", category: "clothing" },
  { korean: "비키니", gloss: "bikini", emoji: "👙", category: "clothing" },
  { korean: "샌들", gloss: "sandal", emoji: "👡", category: "clothing" },
  { korean: "농구", gloss: "basketball", emoji: "🏀", category: "activity" },
  { korean: "야구", gloss: "baseball", emoji: "⚾", category: "activity" },
  { korean: "테니스", gloss: "tennis", emoji: "🎾", category: "activity" },
  { korean: "배구", gloss: "volleyball", emoji: "🏐", category: "activity" },
  { korean: "골프", gloss: "golf", emoji: "⛳", category: "activity" },
  { korean: "볼링", gloss: "bowling", emoji: "🎳", category: "activity" },
  { korean: "다트", gloss: "darts", emoji: "🎯", category: "activity" },
  { korean: "당구", gloss: "billiards", emoji: "🎱", category: "activity" },
  { korean: "트로피", gloss: "trophy", emoji: "🏆", category: "activity" },
  { korean: "메달", gloss: "medal", emoji: "🏅", category: "activity" },
  { korean: "스키", gloss: "ski", emoji: "🎿", category: "activity" },
  { korean: "권투", gloss: "boxing", emoji: "🥊", category: "activity" },
  { korean: "낚시", gloss: "fishing", emoji: "🎣", category: "activity" },
  { korean: "하키", gloss: "hockey", emoji: "🏒", category: "activity" },
  { korean: "배드민턴", gloss: "badminton", emoji: "🏸", category: "activity" },
  { korean: "탁구", gloss: "table tennis", emoji: "🏓", category: "activity" },
  { korean: "럭비", gloss: "rugby", emoji: "🏉", category: "activity" },
  { korean: "미식축구", gloss: "football", emoji: "🏈", category: "activity" },
  { korean: "크리켓", gloss: "cricket", emoji: "🏏", category: "activity" },
  { korean: "스케이트", gloss: "ice skate", emoji: "⛸️", category: "activity" },
  { korean: "연", gloss: "kite", emoji: "🪁", category: "activity" },
  { korean: "요요", gloss: "yo-yo", emoji: "🪀", category: "activity" },
  { korean: "주사위", gloss: "dice", emoji: "🎲", category: "activity" },
  { korean: "퍼즐", gloss: "puzzle", emoji: "🧩", category: "activity" },
  { korean: "인형", gloss: "teddy bear", emoji: "🧸", category: "activity" },
  { korean: "게임기", gloss: "game controller", emoji: "🎮", category: "activity" },
  { korean: "불꽃놀이", gloss: "fireworks", emoji: "🎆", category: "activity" },
  { korean: "폭죽", gloss: "firecracker", emoji: "🧨", category: "activity" },
  { korean: "스케이트보드", gloss: "skateboard", emoji: "🛹", category: "activity" },
  { korean: "기타", gloss: "guitar", emoji: "🎸", category: "music" },
  { korean: "피아노", gloss: "piano", emoji: "🎹", category: "music" },
  { korean: "드럼", gloss: "drum", emoji: "🥁", category: "music" },
  { korean: "트럼펫", gloss: "trumpet", emoji: "🎺", category: "music" },
  { korean: "색소폰", gloss: "saxophone", emoji: "🎷", category: "music" },
  { korean: "바이올린", gloss: "violin", emoji: "🎻", category: "music" },
  { korean: "마이크", gloss: "microphone", emoji: "🎤", category: "music" },
  { korean: "헤드폰", gloss: "headphones", emoji: "🎧", category: "music" },
  { korean: "아코디언", gloss: "accordion", emoji: "🪗", category: "music" },
  { korean: "밴조", gloss: "banjo", emoji: "🪕", category: "music" },
  { korean: "음표", gloss: "music note", emoji: "🎵", category: "music" },
  { korean: "마라카스", gloss: "maracas", emoji: "🪇", category: "music" },
  { korean: "병원", gloss: "hospital", emoji: "🏥", category: "place" },
  { korean: "은행", gloss: "bank", emoji: "🏦", category: "place" },
  { korean: "호텔", gloss: "hotel", emoji: "🏨", category: "place" },
  { korean: "교회", gloss: "church", emoji: "⛪", category: "place" },
  { korean: "성", gloss: "castle", emoji: "🏰", category: "place" },
  { korean: "공장", gloss: "factory", emoji: "🏭", category: "place" },
  { korean: "우체국", gloss: "post office", emoji: "🏤", category: "place" },
  { korean: "백화점", gloss: "department store", emoji: "🏬", category: "place" },
  { korean: "편의점", gloss: "convenience store", emoji: "🏪", category: "place" },
  { korean: "다리", gloss: "bridge", emoji: "🌉", category: "place" },
  { korean: "분수", gloss: "fountain", emoji: "⛲", category: "place" },
  { korean: "관람차", gloss: "ferris wheel", emoji: "🎡", category: "place" },
  { korean: "롤러코스터", gloss: "roller coaster", emoji: "🎢", category: "place" },
  { korean: "텐트", gloss: "tent", emoji: "⛺", category: "place" },
  { korean: "모스크", gloss: "mosque", emoji: "🕌", category: "place" },
  { korean: "신전", gloss: "temple", emoji: "🏛️", category: "place" },
  { korean: "동상", gloss: "statue", emoji: "🗽", category: "place" },
  { korean: "탑", gloss: "tower", emoji: "🗼", category: "place" },
  { korean: "경기장", gloss: "stadium", emoji: "🏟️", category: "place" },
  { korean: "서커스", gloss: "circus", emoji: "🎪", category: "place" },
  { korean: "아파트", gloss: "apartment", emoji: "🏢", category: "place" },
  { korean: "절", gloss: "temple (asian)", emoji: "🏯", category: "place" },
  { korean: "책", gloss: "book", emoji: "📖", category: "object" },
  { korean: "시계", gloss: "clock", emoji: "⏰", category: "object" },
  { korean: "집", gloss: "house", emoji: "🏠", category: "object" },
  { korean: "학교", gloss: "school", emoji: "🏫", category: "object" },
  { korean: "가방", gloss: "bag", emoji: "🎒", category: "object" },
  { korean: "돈", gloss: "money", emoji: "💰", category: "object" },
  { korean: "열쇠", gloss: "key", emoji: "🔑", category: "object" },
  { korean: "우산", gloss: "umbrella", emoji: "☂️", category: "object" },
  { korean: "선물", gloss: "gift", emoji: "🎁", category: "object" },
  { korean: "카메라", gloss: "camera", emoji: "📷", category: "object" },
  { korean: "전화", gloss: "phone", emoji: "📱", category: "object" },
  { korean: "컴퓨터", gloss: "computer", emoji: "💻", category: "object" },
  { korean: "텔레비전", gloss: "television", emoji: "📺", category: "object" },
  { korean: "신발", gloss: "shoes", emoji: "👟", category: "object" },
  { korean: "모자", gloss: "hat", emoji: "🧢", category: "object" },
  { korean: "안경", gloss: "glasses", emoji: "👓", category: "object" },
  { korean: "옷", gloss: "clothes", emoji: "👕", category: "object" },
  { korean: "바지", gloss: "pants", emoji: "👖", category: "object" },
  { korean: "양말", gloss: "socks", emoji: "🧦", category: "object" },
  { korean: "침대", gloss: "bed", emoji: "🛏️", category: "object" },
  { korean: "의자", gloss: "chair", emoji: "🪑", category: "object" },
  { korean: "문", gloss: "door", emoji: "🚪", category: "object" },
  { korean: "풍선", gloss: "balloon", emoji: "🎈", category: "object" },
  { korean: "공", gloss: "ball", emoji: "⚽", category: "object" },
  { korean: "연필", gloss: "pencil", emoji: "✏️", category: "object" },
  { korean: "가위", gloss: "scissors", emoji: "✂️", category: "object" },
  { korean: "지도", gloss: "map", emoji: "🗺️", category: "object" },
  { korean: "편지", gloss: "letter", emoji: "✉️", category: "object" },
  { korean: "약", gloss: "medicine", emoji: "💊", category: "object" },
  { korean: "비누", gloss: "soap", emoji: "🧼", category: "object" },
  { korean: "접시", gloss: "plate", emoji: "🍽️", category: "object" },
  { korean: "숟가락", gloss: "spoon", emoji: "🥄", category: "object" },
  { korean: "칼", gloss: "knife", emoji: "🔪", category: "object" },
  { korean: "냄비", gloss: "pot", emoji: "🍲", category: "object" },
  { korean: "컵", gloss: "cup", emoji: "🥤", category: "object" },
  { korean: "양초", gloss: "candle", emoji: "🕯️", category: "object" },
  { korean: "전구", gloss: "light bulb", emoji: "💡", category: "object" },
  { korean: "배터리", gloss: "battery", emoji: "🔋", category: "object" },
  { korean: "손전등", gloss: "flashlight", emoji: "🔦", category: "object" },
  { korean: "망원경", gloss: "telescope", emoji: "🔭", category: "object" },
  { korean: "현미경", gloss: "microscope", emoji: "🔬", category: "object" },
  { korean: "저울", gloss: "scale", emoji: "⚖️", category: "object" },
  { korean: "온도계", gloss: "thermometer", emoji: "🌡️", category: "object" },
  { korean: "상자", gloss: "box", emoji: "📦", category: "object" },
  { korean: "거울", gloss: "mirror", emoji: "🪞", category: "object" },
  { korean: "빗자루", gloss: "broom", emoji: "🧹", category: "object" },
  { korean: "양동이", gloss: "bucket", emoji: "🪣", category: "object" },
  { korean: "칫솔", gloss: "toothbrush", emoji: "🪥", category: "object" },
  { korean: "립스틱", gloss: "lipstick", emoji: "💄", category: "object" },
  { korean: "보석", gloss: "gem", emoji: "💎", category: "object" },
  { korean: "자물쇠", gloss: "lock", emoji: "🔒", category: "object" },
  { korean: "망치", gloss: "hammer", emoji: "🔨", category: "object" },
  { korean: "렌치", gloss: "wrench", emoji: "🔧", category: "object" },
  { korean: "나사", gloss: "screw", emoji: "🔩", category: "object" },
  { korean: "자석", gloss: "magnet", emoji: "🧲", category: "object" },
  { korean: "사다리", gloss: "ladder", emoji: "🪜", category: "object" },
  { korean: "종", gloss: "bell", emoji: "🔔", category: "object" },
  { korean: "돋보기", gloss: "magnifier", emoji: "🔍", category: "object" },
  { korean: "깃발", gloss: "flag", emoji: "🚩", category: "object" },
  { korean: "톱니바퀴", gloss: "gear", emoji: "⚙️", category: "object" },
  { korean: "톱", gloss: "saw", emoji: "🪚", category: "object" },
  { korean: "드라이버", gloss: "screwdriver", emoji: "🪛", category: "object" },
  { korean: "도끼", gloss: "axe", emoji: "🪓", category: "object" },
  { korean: "곡괭이", gloss: "pickaxe", emoji: "⛏️", category: "object" },
  { korean: "체인", gloss: "chain", emoji: "⛓️", category: "object" },
  { korean: "방패", gloss: "shield", emoji: "🛡️", category: "object" },
  { korean: "단검", gloss: "dagger", emoji: "🗡️", category: "object" },
  { korean: "활", gloss: "bow", emoji: "🏹", category: "object" },
  { korean: "폭탄", gloss: "bomb", emoji: "💣", category: "object" },
  { korean: "변기", gloss: "toilet", emoji: "🚽", category: "object" },
  { korean: "욕조", gloss: "bathtub", emoji: "🛁", category: "object" },
  { korean: "샤워기", gloss: "shower", emoji: "🚿", category: "object" },
  { korean: "소파", gloss: "couch", emoji: "🛋️", category: "object" },
  { korean: "램프", gloss: "lamp", emoji: "🪔", category: "object" },
  { korean: "액자", gloss: "frame", emoji: "🖼️", category: "object" },
  { korean: "두루마리", gloss: "toilet paper", emoji: "🧻", category: "object" },
  { korean: "스펀지", gloss: "sponge", emoji: "🧽", category: "object" },
  { korean: "소화기", gloss: "extinguisher", emoji: "🧯", category: "object" },
  { korean: "면도기", gloss: "razor", emoji: "🪒", category: "object" },
  { korean: "노트", gloss: "notebook", emoji: "📓", category: "object" },
  { korean: "신문", gloss: "newspaper", emoji: "📰", category: "object" },
  { korean: "펜", gloss: "pen", emoji: "🖊️", category: "object" },
  { korean: "크레용", gloss: "crayon", emoji: "🖍️", category: "object" },
  { korean: "붓", gloss: "paintbrush", emoji: "🖌️", category: "object" },
  { korean: "자", gloss: "ruler", emoji: "📏", category: "object" },
  { korean: "삼각자", gloss: "triangle ruler", emoji: "📐", category: "object" },
  { korean: "폴더", gloss: "folder", emoji: "📁", category: "object" },
  { korean: "서류", gloss: "document", emoji: "📄", category: "object" },
  { korean: "클립", gloss: "paperclip", emoji: "📎", category: "object" },
  { korean: "압정", gloss: "pushpin", emoji: "📌", category: "object" },
  { korean: "메모", gloss: "memo", emoji: "📝", category: "object" },
  { korean: "책갈피", gloss: "bookmark", emoji: "🔖", category: "object" },
  { korean: "신용카드", gloss: "credit card", emoji: "💳", category: "object" },
  { korean: "동전", gloss: "coin", emoji: "🪙", category: "object" },
  { korean: "지폐", gloss: "banknote", emoji: "💵", category: "object" },
  { korean: "영수증", gloss: "receipt", emoji: "🧾", category: "object" },
  { korean: "계산기", gloss: "abacus", emoji: "🧮", category: "object" },
  { korean: "키보드", gloss: "keyboard", emoji: "⌨️", category: "object" },
  { korean: "마우스", gloss: "mouse (PC)", emoji: "🖱️", category: "object" },
  { korean: "프린터", gloss: "printer", emoji: "🖨️", category: "object" },
  { korean: "라디오", gloss: "radio", emoji: "📻", category: "object" },
  { korean: "디스크", gloss: "CD", emoji: "💿", category: "object" },
  { korean: "플로피", gloss: "floppy disk", emoji: "💾", category: "object" },
  { korean: "플러그", gloss: "plug", emoji: "🔌", category: "object" },
  { korean: "안테나", gloss: "antenna", emoji: "📡", category: "object" },
  { korean: "손목시계", gloss: "watch", emoji: "⌚", category: "object" },
  { korean: "모래시계", gloss: "hourglass", emoji: "⏳", category: "object" },
  { korean: "손", gloss: "hand", emoji: "✋", category: "body" },
  { korean: "발", gloss: "foot", emoji: "🦶", category: "body" },
  { korean: "입", gloss: "mouth", emoji: "👄", category: "body" },
  { korean: "귀", gloss: "ear", emoji: "👂", category: "body" },
  { korean: "코", gloss: "nose", emoji: "👃", category: "body" },
  { korean: "심장", gloss: "heart", emoji: "🫀", category: "body" },
  { korean: "뇌", gloss: "brain", emoji: "🧠", category: "body" },
  { korean: "이빨", gloss: "tooth", emoji: "🦷", category: "body" },
  { korean: "혀", gloss: "tongue", emoji: "👅", category: "body" },
  { korean: "뼈", gloss: "bone", emoji: "🦴", category: "body" },
  { korean: "근육", gloss: "muscle", emoji: "💪", category: "body" },
  { korean: "발자국", gloss: "footprints", emoji: "👣", category: "body" },
  { korean: "폐", gloss: "lungs", emoji: "🫁", category: "body" },
];
